services:
  - type: web
    name: waldy-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    plan: starter
    region: oregon
    healthCheckPath: /health
